name: Deploy to main

on:
  schedule:
    - cron: 0 18 * * * # Run at 8am every day

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: diillson/auto-pull-request@latest
        with:
            source_branch: "devel"                            # If blank, default: triggered branch
            destination_branch: "main"                        # If blank, default: master
            pr_title: "DEVEL"                                 # Title of pull request
            pr_allow_empty: false                             # Creates pull request even if there are no changes
            github_token: ${{ secrets.CUSTOM_GA_TOKEN }}      # If blank, default: secrets.GITHUB_TOKEN

