on:
    pull_request:
      branches:
        - "main"
  
jobs:
    job1:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Validate PR source branch
          run: |
            SOURCE_BRANCH=$(jq -r '.base.ref' $GITHUB_EVENT_PATH)
            if [ "$SOURCE_BRANCH" != "devel" ]; then
              echo "Solo se pueden hacer PRs a "main" desde "devel", por favor revisar"
              exit 1
            fi
          env:
            GITHUB_EVENT_PATH: ${{ github.event_path }}

    job2:
      needs: job1
      runs-on: ubuntu-latest

      steps:
        - uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.CUSTOM_GA_TOKEN }}
            script: |
              const creator = context.payload.sender.login;
              try {
                const result = await github.rest.teams.getMembershipForUserInOrg({
                  org: 'xepelinapp',
                  team_slug: 'data-crowd',
                  username: creator
                });
              } catch (error) {
                const pullRequestNumber = context.payload.pull_request.number;
                const owner = context.repo.owner;
                const repo = context.repo.repo;
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: pullRequestNumber,
                  body: 'Thank you for your contribution! We are closing this pull request as per our workflow.'
                });
                await github.rest.pulls.update({
                  owner,
                  repo,
                  pull_number: pullRequestNumber,
                  state: 'closed'
                });
              };


