#name: Check PR Owner Team

#on:
  #workflow_dispatch:
  #pull_request_target:
    #types: [opened, synchronize, reopened]
    #branches:
      #- "main"

#jobs:
 # my_job:
  #  runs-on: ubuntu-latest
   # steps:
    #  - uses: actions/github-script@v7
     #   with:
      #    github-token: ${{ secrets.CUSTOM_GA_TOKEN }}
       #   script: |
        #    const creator = context.payload.sender.login;
         #   try {
          #    const result = await github.rest.teams.getMembershipForUserInOrg({
             #   org: 'xepelinapp',
              #  team_slug: 'data-crowd',
               # username: creator
              #});
            #} catch (error) {
             # const pullRequestNumber = context.payload.pull_request.number;
              #const owner = context.repo.owner;
              #const repo = context.repo.repo;
              #await github.rest.issues.createComment({
               # owner,
                #repo,
                #issue_number: pullRequestNumber,
                #body: 'Thank you for your contribution! We are closing this pull request as per our workflow.'
              #});
              #await github.rest.pulls.update({
               # owner,
                #repo,
                #pull_number: pullRequestNumber,
                #state: 'closed'
             # });
            #};