name: Add Label to Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    runs-on: [self-hosted, linux, X64, k8s]

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CUSTOM_GA_TOKEN }}
          script: |
            const creator = context.payload.sender.login;
            console.log(creator);
            const result = await github.rest.teams.getMembershipForUserInOrg({
              org: 'xepelinapp',
              team_slug: 'data-crowd',
              username: creator
            });
            console.log(creator, result);


     # - name: Add Label
       # run: |
         # echo "${{ steps.checkUserMember.outputs.isMember }}"
       # uses: actions/labeler@v5
       # with:
        #  repo-token: ${{ secrets.CUSTOM_GA_TOKEN }}
         # configuration-path: .github/labeler.yml


  
