name: Add Label to Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        id: checkUserMember
        with:
          github-token: ${{ secrets.CUSTOM_GA_TOKEN }}
          script: |
            const creator = context.payload.sender.login;
            console.log(creator);
            const result = await github.rest.teams.getMembershipForUserInOrg({
              org: 'xepelinapp',
              team_slug: 'data-crowd',
              username: creator
            });
            console.log(creator, result);


      - name: Add Label
        if: ${{ steps.checkUserMember.outputs.state == 'active' }}
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.CUSTOM_GA_TOKEN }}
          configuration-path: .github/labeler.yml


  
