name: Add Label to Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        id: checkUserMember
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          script: |
            const teamLabels = {
              'data-crowd': 'DC',
              'data-bi': 'BI'
            }
            keys = Object.keys(teamLabels)

            const creator = context.payload.sender.login;
            const pullRequestNumber = context.payload.pull_request.number;

            for (var i = 0; i < keys.length; i++) {
              const result = await github.rest.teams.getMembershipForUserInOrg({
                org: 'xepelinapp',
                team_slug: keys[i],
                username: creator
              });
              if (result.data.state === 'active'){
                const labelToAdd = teamLabels[keys[i]];
                await github.rest.issues.addLabels({
                  owner: 'xepelinapp',
                  repo: 'datacrowd-pr_owner_checker',
                  issue_number: pullRequestNumber,
                  labels: [labelToAdd]
                })
              };
            };   



  
