name: Add Label to Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check Team Membership
        uses: tspascoal/get-user-teams-membership@v3
        id: checkUserMember
        with: 
          team: 'data-crowd'
          username: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GA_TOKEN }}

      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
        name: Add Label
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.CUSTOM_GA_TOKEN }}
          configuration-path: .github/labeler.yml
  
