name: Add Label to Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Team Membership
        run: |
          ORG=xepelinapp
          TEAM=data-crowd

          TEAM_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/orgs/$ORG/teams | jq -r ".[] | select(.slug == \"$TEAM\") | .id")

          MEMBERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/teams/$TEAM_ID/members | jq -r ".[].login")

          if [[ "$MEMBERS" == *"$GITHUB_ACTOR"* ]]; then
            MEMBER=true
          else
            MEMBER=false
          fi

      - name: Add Label
        if: ${{ steps.check-membership-and-add-label.outputs.MEMBER == 'true' }}
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
  
