name: Add Label to Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Check Team Membership
        run: |
          organization="xepelin"
          team="data-crowd"
          user="${{ github.event.pull_request.user.login }}"

          if [[ $(curl -sSL "https://api.github.com/orgs/${organization}/teams/${team}/members/${user}" | jq -r '.login') == "${user}" ]]; then
            MEMBER=true
          else
            MEMBER=false
          fi
          echo "$MEMBER"

      - name: Add Label
        if: ${{ steps.check-membership-and-add-label.outputs.MEMBER == 'true' }}
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
  
